# Generated by Django 4.2.10 on 2025-04-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('asset_type', models.CharField(choices=[('STOCK', 'Stock'), ('MF', 'Mutual Fund'), ('CRYPTO', 'Cryptocurrency')], max_length=20)),
                ('asset_name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending'), ('Failed', 'Failed')], max_length=20)),
                ('order_type', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit'), ('STOP_LOSS', 'Stop Loss')], max_length=10)),
            ],
        ),
    ]
